FROM python:3.12-slim
WORKDIR /backend
RUN apt update

COPY /backend/requirements.txt ./

RUN pip install -r requirements.txt

EXPOSE 8000

COPY /backend .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

