FROM node:20-alpine
WORKDIR /app
ENV PATH app/node_modules/.bin:$PATH
COPY /frontend/package.json ./

RUN npm install

COPY /frontend .

RUN npm run build

CMD ["npm", "run", "dev"]

EXPOSE 3000